apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "greengpt-ui-ui.fullname" . }}
  labels:
    {{- include "greengpt-ui-ui.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "greengpt-ui-ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "greengpt-ui-ui.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          serviceAccountName: {{ .Values.serviceAccount.name }}  
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.ports.containerPort }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: {{ .Values.ports.containerPort }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: {{ .Values.ports.containerPort }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ quote $value }}
            {{- end }}
          resources:
            limits:
              cpu: {{ .Values.resourcesLimits.cpu }}
              memory: {{ .Values.resourcesLimits.memory }}
            requests:
              cpu: {{ .Values.requestsResources.cpu }}
              memory: {{ .Values.requestsResources.memory }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
          volumeMounts:
          {{- if .Values.configMap.createNginxconfConfigmap }}
          - name: nginx-conf
            mountPath: {{ .Values.volumeMounts.nginxConfPath }}
            subPath: {{ .Values.volumeMounts.nginxConfsubPath }}
          {{- end }}
        {{- if .Values.exporter.enable }}
        - name: {{ .Values.exporter.name }}
          image:  "{{ .Values.exporter.image.repository }}:{{ .Values.exporter.image.tag }}"
          imagePullPolicy: {{ .Values.exporter.image.pullPolicy }}
          ports:
          - containerPort:  {{ .Values.exporter.ports.containerPort }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.exporter.ports.containerPort }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          env:
            {{- range $key, $value := .Values.exporter.env }}
            - name: {{ $key }}
              value: {{ quote $value }}
            {{- end }}
        {{- end }} 
          resources:
            limits:
              cpu: {{ .Values.exporter.resources.limits.cpu }}
              memory: {{ .Values.exporter.resources.limits.memory }}
            requests:
              cpu: {{ .Values.exporter.resources.requests.cpu }}
              memory: {{ .Values.exporter.resources.requests.memory }}
      volumes:
      {{- if .Values.configMap.createNginxconfConfigmap }}
      - name: nginx-conf
        configMap:
          defaultMode: {{ .Values.configMap.defaultMode }}
          name: {{ .Release.Name }}-cm
      {{- end }}
      {{- if .Values.configMap.createkeycloakContextConfigmap }}
      - name: context-config
        configMap:
          defaultMode: {{ .Values.configMap.defaultMode }}
          name: {{ .Release.Name }}-context-cm
      {{- end }}
