{{- if .Values.virtualService.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "hrms-ui-ui.fullname" . }}
spec:
  hosts:
  - {{ .Values.gatewayServers.hosts }}
  gateways:
  - {{ .Release.Name }}-gw
  http:
  - match:
    - uri:
        prefix: {{ .Values.virtualService.context }}
    route:
    - destination:
        port:
          number: {{ .Values.service.port }}
        host: {{ include "hrms-ui-ui.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
{{- end }}
