ALTER TABLE `EMPLOYEE_GOALS_DETAILS` MODIFY COLUMN `EMPLOYEE_STATUS` ENUM('Not Started', 'On Track', 'At Risk', 'Deferred', 'Completed', 'Off Track') DEFAULT 'Not Started', MODIFY COLUMN `MANAGER_STATUS` ENUM('Not Started', 'On Track', 'At Risk', 'Deferred', 'Completed', 'Off Track') DEFAULT 'Not Started'; 

ALTER TABLE BUSINESS_EXPENSE ADD COLUMN OTHER_EXPENSE_BANK_REQUEST_ID INT DEFAULT NULL COMMENT 'Stores Id of Other Expense Bank Request'; 

ALTER TABLE BUSINESS_TRIP ADD COLUMN OTHER_EXPENSE_BANK_REQUEST_ID INT DEFAULT NULL COMMENT 'Stores Id of Other Expense Bank Request'; 

ALTER TABLE `HR_BENEFITS` ADD COLUMN `OTHER_EXPENSE_BANK_REQUEST_ID` INT DEFAULT NULL COMMENT 'Stores Id of Other Expense Bank Request’; 

ALTER TABLE BUSINESS_TRIP ADD COLUMN TRAVEL_SCOPE ENUM('INTERNAL', 'EXTERNAL') DEFAULT NULL; 

ALTER TABLE PAYROLL_RUN ADD COLUMN `TOTAL_BASIC_SALARY` double DEFAULT NULL COMMENT 'Total basic salary for the payroll', ADD COLUMN `TOTAL_ALLOWANCES` double DEFAULT NULL COMMENT 'Total allowances amount for the payroll'; 

CREATE TABLE `JOB_APPLICATION_BATCH` (   `ID` int NOT NULL AUTO_INCREMENT,   `PROCESS_INSTANCE_ID` varchar(100) DEFAULT NULL,   `WORKFLOW_STAGE` varchar(100) DEFAULT NULL,   `CREATED_TIME` datetime(6) DEFAULT NULL,   `MODIFIED_TIME` datetime(6) DEFAULT NULL,   `CREATOR` int DEFAULT NULL,   `LAST_MODIFIER` int DEFAULT NULL,   PRIMARY KEY (`ID`),   KEY `FKryunt4ywp525bi3f53jifd5qj5amwq` (`CREATOR`),   KEY `FKhfqj4fkf32oyx6srfdihcvdfdfq2w` (`LAST_MODIFIER`),   CONSTRAINT `FKhfqj4fkf32oyx6srfdihcvdfdfq2w` FOREIGN KEY (`LAST_MODIFIER`) REFERENCES `User` (`ID`),   CONSTRAINT `FKryunt4ywp525bi3f53jifd5qj5amwq` FOREIGN KEY (`CREATOR`) REFERENCES `User` (`ID`) ); 

ALTER TABLE JOB_APPLICATION ADD COLUMN JOB_APPLICATION_BATCH_ID INT DEFAULT NULL; 

  

ALTER TABLE JOB_APPLICATION 
 ADD CONSTRAINT FK_JOB_APPLICATION_JOB_APPLICATION_BATCH FOREIGN KEY (JOB_APPLICATION_BATCH_ID) REFERENCES JOB_APPLICATION_BATCH(ID); 

 

ALTER TABLE `EMPLOYEE_GOALS_DETAILS` MODIFY `TEXT1` TEXT COMMENT 'Stores the Prompt given',MODIFY `DESCRIPTION` VARCHAR(500) DEFAULT NULL COMMENT 'Stores Description given by prompt',MODIFY `SUCCESS_CRITERIA` VARCHAR(500) DEFAULT NULL COMMENT 'Stores Success Criteria given by prompt', MODIFY `TITLE` VARCHAR(200) DEFAULT NULL COMMENT 'Title of the employee goal'; 

 

ALTER TABLE BUSINESS_EXPENSE ADD COLUMN REMARK LONGTEXT COMMENT'It stores the remark'; 

ALTER TABLE HR_BENEFITS ADD COLUMN REMARK LONGTEXT COMMENT'It stores the remark'; 

ALTER TABLE INTERVIEW ADD COLUMN INTERVIEWER_RECRUITER INT DEFAULT NULL; 

ALTER TABLE INTERVIEW ADD CONSTRAINT FK_INTERVIEW_INTERVIEWER_RECRUITER FOREIGN KEY (INTERVIEWER_RECRUITER) REFERENCES EMPLOYEE(ID); 

ALTER TABLE INTERVIEW ADD COLUMN INTERVIEWER_MANAGER INT DEFAULT NULL; 

ALTER TABLE INTERVIEW ADD CONSTRAINT FK_INTERVIEW_INTERVIEWER_MANAGER FOREIGN KEY (INTERVIEWER_MANAGER) REFERENCES EMPLOYEE(ID); 

ALTER TABLE INTERVIEW RENAME COLUMN CANDIDATE_ID TO APPLICANT_ID; 

ALTER TABLE EMPLOYEE_DAILY_ATTENDANCE MODIFY COLUMN STATUS ENUM('Present', 'Absent', 'Leave', 'Leave Cancelled') COMMENT 'Stores Type of Entry'; 

UPDATE APPLICANT SET APPLICANT_STATUS = NULL; 

ALTER TABLE APPLICANT  
CHANGE COLUMN APPLICANT_STATUS APPLICANT_STATUS  
ENUM('Applied', 'Interview to be scheduled', 'Interview scheduled', 'Interview in progress', 'Interview completed', 'Offer planned', 'BGC initiated', 'BGC approved', 'BGC rejected', 'Offer made', 'Offer accepted', 'Offer rejected', 'Hired', 'Rejected in interview')  
Default NULL;  

ALTER TABLE JOB_APPLICATION_BATCH ADD COLUMN JOB_OPENING_FK INT; 
ALTER TABLE JOB_APPLICATION_BATCH  ADD CONSTRAINT JOB_APPLICATION_BATCH_FK_ibfk44 FOREIGN KEY (JOB_OPENING_FK)  REFERENCES JOB_OPENING(ID); 

UPDATE JOB_OPENING SET HIRING_MANAGER=NULL; 
ALTER TABLE JOB_OPENING MODIFY COLUMN HIRING_MANAGER INT; 
ALTER TABLE JOB_OPENING  ADD CONSTRAINT JOB_OPENING_FK_ibfk44 FOREIGN KEY (HIRING_MANAGER)  REFERENCES EMPLOYEE(ID); 

ALTER TABLE INTERVIEW ADD COLUMN INTERVIEW_START_TIME datetime(6) DEFAULT NULL; 

ALTER TABLE INTERVIEW ADD COLUMN INTERVIEW_END_TIME datetime(6) DEFAULT NULL; 

ALTER TABLE `APPLICANT_EDUCATION` ADD COLUMN `ATTACHMENT1` VARCHAR(200) DEFAULT NULL COMMENT'attachment to upload file', ADD COLUMN `ATTACHMENT2` VARCHAR(200) DEFAULT NULL COMMENT'attachment to upload file'; 

  

ALTER TABLE `APPLICANT_CERTIFICATIONS` ADD COLUMN `ATTACHMENT1` VARCHAR(200) DEFAULT NULL COMMENT'attachment to upload file', ADD COLUMN `ATTACHMENT2` VARCHAR(200) DEFAULT NULL COMMENT'attachment to upload file'; 

  

ALTER TABLE `APPLICANT_EXPERIENCE` ADD COLUMN `ATTACHMENT1` VARCHAR(200) DEFAULT NULL COMMENT'attachment to upload file', ADD COLUMN `ATTACHMENT2` VARCHAR(200) DEFAULT NULL COMMENT'attachment to upload file'; 
 

ALTER TABLE `APPLICANT_EDUCATION` ADD COLUMN `GRADE` INT DEFAULT NULL ; 

ALTER TABLE `BUSINESS_EXPENSE` ADD COLUMN `EXPENSE_CATEGORY` ENUM('Individual','Business Trip') DEFAULT 'Individual'; 

ALTER TABLE `BUSINESS_EXPENSE` ADD COLUMN `BUSINESS_TRIP_ID` INT DEFAULT NULL; 
 ALTER TABLE `BUSINESS_EXPENSE` ADD CONSTRAINT `FK_FOR_BUSINESS_EXPENSE_BUSINESS_TRIP`   FOREIGN KEY (`BUSINESS_TRIP_ID`)   REFERENCES `BUSINESS_TRIP` (`ID`); 

  

CREATE TABLE `APPLICANT_NATIONAL_IDENTIFICATION` (   `ID` int NOT NULL AUTO_INCREMENT,   `DELETED` tinyint(1) NOT NULL DEFAULT '0',   `TYPE` varchar(100) DEFAULT NULL,   `IDENTIFICATION_NUMBER` varchar(50) DEFAULT NULL,   `SCANNED_IMAGE` varchar(255) DEFAULT NULL,   `BORDER_NUMBER` varchar(100) DEFAULT NULL,   `EXPIRY_DATE` datetime DEFAULT NULL,   `APPLICANT_FK` int DEFAULT NULL,   `CREATED_TIME` datetime(6) DEFAULT NULL,   `MODIFIED_TIME` datetime(6) DEFAULT NULL,   `CREATOR` int DEFAULT NULL,   `LAST_MODIFIER` int DEFAULT NULL,   PRIMARY KEY (`ID`),   KEY `APPLICANT_FK` (`APPLICANT_FK`),   KEY `FKnn0l60sqh0s0by7j7ypqu7btxu` (`CREATOR`),   KEY `FK10xx3qf8l03l6mi3gd8f6tvu1c` (`LAST_MODIFIER`),   CONSTRAINT `applicant_national_identification_ibfk1_1` FOREIGN KEY (`APPLICANT_FK`) REFERENCES `APPLICANT` (`ID`),   CONSTRAINT `FK10xx3qf8l03l6mi3gd8f6tvu1c` FOREIGN KEY (`LAST_MODIFIER`) REFERENCES `User` (`ID`),   CONSTRAINT `FKnn0l60sqh0s0by7j7ypqu7btxu` FOREIGN KEY (`CREATOR`) REFERENCES `User` (`ID`) ); 


ALTER TABLE JOB_APPLICATION  
 MODIFY COLUMN APPLICATION_STATUS enum('Applied','Interview to be scheduled','Interview scheduled','Interview in progress','Interview completed','Offer planned','BGC initiated','BGC approved','BGC rejected','Offer made','Offer accepted','Offer rejected','Hired','Rejected in interview','Rejected') DEFAULT NULL; 

ALTER TABLE APPLICANT  
 MODIFY COLUMN APPLICANT_STATUS enum('Applied','Interview to be scheduled','Interview scheduled','Interview in progress','Interview completed','Offer planned','BGC initiated','BGC approved','BGC rejected','Offer made','Offer accepted','Offer rejected','Hired','Rejected in interview','Rejected') DEFAULT NULL; 

ALTER TABLE INTERVIEW ADD COLUMN APPLICANT_SCHEDULE bit(1) DEFAULT b'0' COMMENT'identify applicant scheduled the interview or not'; 
 
ALTER TABLE APPLICANT  MODIFY COLUMN TEXT1 LONGTEXT; 


ALTER TABLE JOB_APPLICATION  MODIFY COLUMN APPLICATION_STATUS enum('Applied','Interview to be scheduled','Interview scheduled','Interview in progress','Interview completed','Offer planned','BGC initiated','BGC approved','BGC rejected','Offer made','Offer accepted','Offer rejected','Hired','Rejected in interview','Rejected','NEW') DEFAULT 'NEW'; 
 
 ALTER TABLE APPLICANT  MODIFY COLUMN APPLICANT_STATUS enum('Applied','Interview to be scheduled','Interview scheduled','Interview in progress','Interview completed','Offer planned','BGC initiated','BGC approved','BGC rejected','Offer made','Offer accepted','Offer rejected','Hired','Rejected in interview','Rejected','NEW') DEFAULT 'NEW'; 


 Alter table INTERVIEW  Add column APPLICANT_SCHEDULED_COUNT  int DEFAULT 0; 
 
 Alter table INTERVIEW drop column APPLICANT_SCHEDULE; 

Alter table INTERVIEW  Add column INTERVIEWER_SCHEDULED_COUNT  int DEFAULT 0; 
