ALTER TABLE EMPLOYEE ADD COLUMN STATE VARCHAR(100) DEFAULT NULL COMMENT'to store the address'; 
 ALTER TABLE EMPLOYEE_AUD ADD COLUMN STATE VARCHAR(100) DEFAULT NULL COMMENT'to store the address';   

ALTER TABLE EMPLOYEE ADD COLUMN ONBOARDING_SPECIALIST_MEETING_TIME DATETIME DEFAULT NULL, ADD COLUMN IQAMA_NUMBER VARCHAR(255) DEFAULT NULL, ADD COLUMN CYBER_SECURITY_SPECIALIST_NAME VARCHAR(255) DEFAULT NULL, ADD COLUMN CYBER_SECURITY_SESSION_DATE DATETIME DEFAULT NULL; 
 ALTER TABLE EMPLOYEE_AUD ADD COLUMN ONBOARDING_SPECIALIST_MEETING_TIME DATETIME DEFAULT NULL, ADD COLUMN IQAMA_NUMBER VARCHAR(255) DEFAULT NULL, ADD COLUMN CYBER_SECURITY_SPECIALIST_NAME VARCHAR(255) DEFAULT NULL, ADD COLUMN CYBER_SECURITY_SESSION_DATE DATETIME DEFAULT NULL; 

 ALTER TABLE RELOCATION ADD COLUMN DISTANCE INT DEFAULT NULL , ADD COLUMN NUMBER_OF_TRAVELLERS INT DEFAULT NULL;  
 ALTER TABLE RELOCATION_AUD ADD COLUMN DISTANCE INT DEFAULT NULL , ADD COLUMN NUMBER_OF_TRAVELLERS INT DEFAULT NULL; 

 ALTER TABLE EMPLOYEE_WORK_EXPERIENCE ADD COLUMN ATTACHMENT1 VARCHAR(200) DEFAULT NULL,ADD COLUMN ATTACHMENT2 VARCHAR(200) DEFAULT NULL; 

 ALTER TABLE EMPLOYEE_COMPLIANCE_LEGAL ADD COLUMN ATTACHMENT1 VARCHAR(200) DEFAULT NULL,ADD COLUMN ATTACHMENT2 VARCHAR(200) DEFAULT NULL,ADD COLUMN ATTACHMENT3 VARCHAR(200) DEFAULT NULL,ADD COLUMN ATTACHMENT4 VARCHAR(200) DEFAULT NULL; 
 ALTER TABLE EMPLOYEE_COMPLIANCE_LEGAL_AUD ADD COLUMN ATTACHMENT1 VARCHAR(200) DEFAULT NULL,ADD COLUMN ATTACHMENT2 VARCHAR(200) DEFAULT NULL,ADD COLUMN ATTACHMENT3 VARCHAR(200) DEFAULT NULL,ADD COLUMN ATTACHMENT4 VARCHAR(200) DEFAULT NULL; 

 DROP TABLE EMPLOYEE_LANGUAGE; 
 DROP TABLE EMPLOYEE_LANGUAGE_AUD; 

CREATE TABLE `EMPLOYEE_LANGUAGE` ( `ID` int NOT NULL AUTO_INCREMENT,   `DELETED` tinyint(1) NOT NULL DEFAULT '0',   `EMPLOYEE_ID` int DEFAULT NULL,   `LANGUAGE_NAME` varchar(200) DEFAULT NULL,   `LANGUAGE_LEVEL` varchar(200) DEFAULT NULL,   `CERTIFICATION_STATUS` varchar(200) DEFAULT NULL,   `SPEAKING_PROFICIENCY` enum('Beginner', 'Intermediate', 'Advanced', 'Native') DEFAULT NULL,   `WRITING_PROFICIENCY` enum('Beginner', 'Intermediate', 'Advanced', 'Native') DEFAULT NULL,   `READING_PROFICIENCY` enum('Beginner', 'Intermediate', 'Advanced', 'Native') DEFAULT NULL,   `LISTENING_PROFICIENCY` enum('Beginner', 'Intermediate', 'Advanced', 'Native') DEFAULT NULL,   `PRIMARY_LANGUAGE` varchar(50) DEFAULT NULL,   `REMARKS` longtext DEFAULT NULL ,   `LANGUAGE_CERTIFICATION` varchar(200) DEFAULT NULL,   `CREATED_TIME` datetime(6) DEFAULT NULL,   `MODIFIED_TIME` datetime(6) DEFAULT NULL,   `CUSTOMER_ID` int DEFAULT NULL,   `CREATOR` int DEFAULT NULL,   `LAST_MODIFIER` int DEFAULT NULL,   PRIMARY KEY (`ID`),   KEY `EMPLOYEE_ID` (`EMPLOYEE_ID`),   KEY `FKgcruli3esfsctlm26gfikr3kr` (`CREATOR`),   KEY `FKii8md9kmrms2fnit66jrndv8t` (`LAST_MODIFIER`),   CONSTRAINT `employee_language_ibfk_1` FOREIGN KEY (`EMPLOYEE_ID`) REFERENCES `EMPLOYEE` (`ID`),   CONSTRAINT `FKgcruli3esfsctlm26gfikr3kr` FOREIGN KEY (`CREATOR`) REFERENCES `User` (`ID`),   CONSTRAINT `FKii8md9kmrms2fnit66jrndv8t` FOREIGN KEY (`LAST_MODIFIER`) REFERENCES `User` (`ID`) ); 

 CREATE TABLE `EMPLOYEE_LANGUAGE_AUD` (   `id` int NOT NULL,   `REV` int NOT NULL,   `REVTYPE` tinyint DEFAULT NULL,   `CREATED_TIME` datetime(6) DEFAULT NULL,   `MODIFIED_TIME` datetime(6) DEFAULT NULL,   `CUSTOMER_ID` int DEFAULT NULL,   `deleted` bit(1) DEFAULT NULL,   `LANGUAGE_NAME` varchar(200) DEFAULT NULL,   `LANGUAGE_LEVEL` varchar(200) DEFAULT NULL,   `CERTIFICATION_STATUS` varchar(200) DEFAULT NULL,   `SPEAKING_PROFICIENCY` enum('Beginner', 'Intermediate', 'Advanced', 'Native') DEFAULT NULL,   `WRITING_PROFICIENCY` enum('Beginner', 'Intermediate', 'Advanced', 'Native') DEFAULT NULL,   `READING_PROFICIENCY` enum('Beginner', 'Intermediate', 'Advanced', 'Native') DEFAULT NULL,   `LISTENING_PROFICIENCY` enum('Beginner', 'Intermediate', 'Advanced', 'Native') DEFAULT NULL,   `PRIMARY_LANGUAGE` varchar(50) DEFAULT NULL,   `REMARKS` longtext DEFAULT NULL ,   `LANGUAGE_CERTIFICATION` varchar(200) DEFAULT NULL,   `CREATOR` int DEFAULT NULL,   `LAST_MODIFIER` int DEFAULT NULL,   `EMPLOYEE_ID` int DEFAULT NULL,   PRIMARY KEY (`REV`,`id`),   CONSTRAINT `FKdwvh5i4llq3erii9etbpk9gja` FOREIGN KEY (`REV`) REFERENCES `REVINFO` (`REV`) ); 

ALTER TABLE EMPLOYEE_CERTIFICATION DROP FOREIGN KEY FK9t9lm2qacidhjlns39u9efo9o; ALTER TABLE EMPLOYEE_CERTIFICATION ADD CONSTRAINT FK9t9lm2qacidhjlns39u9efo9o FOREIGN KEY (CREATOR) REFERENCES User (ID); ALTER TABLE EMPLOYEE_CERTIFICATION DROP FOREIGN KEY FKt57rpn3vwxgtkcy2esyigg20p; ALTER TABLE EMPLOYEE_CERTIFICATION ADD CONSTRAINT FKt57rpn3vwxgtkcy2esyigg20p FOREIGN KEY (LAST_MODIFIER) REFERENCES User (ID); 

ALTER TABLE EMPLOYEE_PROFESSIONAL_LICENCE DROP FOREIGN KEY FKilhe3o0qcg4oiievx0qckfjwf; ALTER TABLE EMPLOYEE_PROFESSIONAL_LICENCE ADD CONSTRAINT FKilhe3o0qcg4oiievx0qckfjwf FOREIGN KEY (CREATOR) REFERENCES User (ID); ALTER TABLE EMPLOYEE_PROFESSIONAL_LICENCE DROP FOREIGN KEY FKj1uyg5xqxc8ixruu5bs4gb0qq; ALTER TABLE EMPLOYEE_PROFESSIONAL_LICENCE ADD CONSTRAINT FKj1uyg5xqxc8ixruu5bs4gb0qq FOREIGN KEY (LAST_MODIFIER) REFERENCES User (ID); 

ALTER TABLE EMPLOYEE_CLEARANCE_CERTIFICATE DROP FOREIGN KEY FKd5qasovtrulqmctbhk2cvi4p2; ALTER TABLE EMPLOYEE_CLEARANCE_CERTIFICATE ADD CONSTRAINT FKd5qasovtrulqmctbhk2cvi4p2 FOREIGN KEY (LAST_MODIFIER) REFERENCES User (ID); ALTER TABLE EMPLOYEE_CLEARANCE_CERTIFICATE DROP FOREIGN KEY FKeydqw9ytalfxu67p389h5gotw; ALTER TABLE EMPLOYEE_CLEARANCE_CERTIFICATE ADD CONSTRAINT FKeydqw9ytalfxu67p389h5gotw FOREIGN KEY (CREATOR) REFERENCES User (ID); 

ALTER TABLE RELOCATION DROP FOREIGN KEY FKa6om8f0pef31dseqd8gk8pgt1; ALTER TABLE RELOCATION ADD CONSTRAINT FKa6om8f0pef31dseqd8gk8pgt1 FOREIGN KEY (CREATOR) REFERENCES User (ID); ALTER TABLE RELOCATION DROP FOREIGN KEY FKmyg4wi16yc3e81jpsot19scud; ALTER TABLE RELOCATION ADD CONSTRAINT FKmyg4wi16yc3e81jpsot19scud FOREIGN KEY (LAST_MODIFIER) REFERENCES User (ID); 

ALTER TABLE FACILITY_MANAGEMENT DROP FOREIGN KEY FK3004st4g5cngwom8am67ka99t; ALTER TABLE FACILITY_MANAGEMENT ADD CONSTRAINT FK3004st4g5cngwom8am67ka99t FOREIGN KEY (LAST_MODIFIER) REFERENCES User (ID); ALTER TABLE FACILITY_MANAGEMENT DROP FOREIGN KEY FKlybfabuvg8c0673n6lckgxwlt; ALTER TABLE FACILITY_MANAGEMENT ADD CONSTRAINT FKlybfabuvg8c0673n6lckgxwlt FOREIGN KEY (CREATOR) REFERENCES User (ID); 


ALTER TABLE WORKFLOW_ACTION CHANGE COLUMN CREATOR CREATOR_FK int default null COMMENT 'The foreign key of the creator user'; 

ALTER TABLE WORKFLOW_ACTION CHANGE COLUMN LAST_MODIFIER MODIFIER_FK int default null COMMENT 'The foreign key of the creator user'; 

ALTER TABLE EMPLOYEE CHANGE `EMPLOYMENT_STATUS` `EMPLOYMENT_STATUS` enum('Active','Inactive','Terminated','In Onboarding') DEFAULT NULL; 

ALTER TABLE `APPLICANT` CHANGE `APPLICANT_SOURCE` `APPLICANT_SOURCE` ENUM( 'Internal-Referral', 'Job-Boards','Career-Sites','Recruitment-Agencies','Social-Media','Direct-Applications', 'Campus-Recruitment','Employee-Referral-Programs', 
'Internal Referral','Job Boards','Career Sites','Recruitment Agencies','Social Media','Direct Applications','Campus Recruitment','Employee Referral Programs') DEFAULT NULL; 
UPDATE APPLICANT SET APPLICANT_SOURCE='Internal-Referral' WHERE APPLICANT_SOURCE='Internal Referral'; 
UPDATE APPLICANT SET APPLICANT_SOURCE='Job-Boards' WHERE APPLICANT_SOURCE='Job Boards'; 
UPDATE APPLICANT SET APPLICANT_SOURCE='Career-Sites' WHERE APPLICANT_SOURCE='Career Sites'; 
UPDATE APPLICANT SET APPLICANT_SOURCE='Recruitment-Agencies' WHERE APPLICANT_SOURCE='Recruitment Agencies'; 
UPDATE APPLICANT SET APPLICANT_SOURCE='Social-Media' WHERE APPLICANT_SOURCE='Social Media'; 
UPDATE APPLICANT SET APPLICANT_SOURCE='Direct-Applications' WHERE APPLICANT_SOURCE='Direct Applications'; 
UPDATE APPLICANT SET APPLICANT_SOURCE='Campus-Recruitment' WHERE APPLICANT_SOURCE='Campus Recruitment'; 
UPDATE APPLICANT SET APPLICANT_SOURCE='Employee-Referral-Programs' WHERE APPLICANT_SOURCE='Employee Referral Programs'; 
ALTER TABLE `APPLICANT` CHANGE `APPLICANT_SOURCE` `APPLICANT_SOURCE` ENUM( 'Internal-Referral', 'Job-Boards','Career-Sites','Recruitment-Agencies','Social-Media','Direct-Applications', 'Campus-Recruitment','Employee-Referral-Programs') DEFAULT NULL; 


ALTER TABLE EMPLOYEE_AUD CHANGE EMPLOYMENT_STATUS EMPLOYMENT_STATUS enum('Active','Inactive','Terminated','In Onboarding') DEFAULT NULL; 

ALTER TABLE APPLICANT_AUD CHANGE APPLICANT_SOURCE APPLICANT_SOURCE ENUM( 'Internal-Referral', 'Job-Boards','Career-Sites','Recruitment-Agencies','Social-Media','Direct-Applications', 'Campus-Recruitment','Employee-Referral-Programs', 'Internal Referral','Job Boards','Career Sites','Recruitment Agencies','Social Media','Direct Applications','Campus Recruitment','Employee Referral Programs') DEFAULT NULL; UPDATE APPLICANT_AUD SET APPLICANT_SOURCE='Internal-Referral' WHERE APPLICANT_SOURCE='Internal Referral'; UPDATE APPLICANT_AUD SET APPLICANT_SOURCE='Job-Boards' WHERE APPLICANT_SOURCE='Job Boards'; UPDATE APPLICANT_AUD SET APPLICANT_SOURCE='Career-Sites' WHERE APPLICANT_SOURCE='Career Sites'; UPDATE APPLICANT_AUD SET APPLICANT_SOURCE='Recruitment-Agencies' WHERE APPLICANT_SOURCE='Recruitment Agencies'; UPDATE APPLICANT_AUD SET APPLICANT_SOURCE='Social-Media' WHERE APPLICANT_SOURCE='Social Media'; UPDATE APPLICANT_AUD SET APPLICANT_SOURCE='Direct-Applications' WHERE APPLICANT_SOURCE='Direct Applications'; UPDATE APPLICANT_AUD SET APPLICANT_SOURCE='Campus-Recruitment' WHERE APPLICANT_SOURCE='Campus Recruitment'; UPDATE APPLICANT_AUD SET APPLICANT_SOURCE='Employee-Referral-Programs' WHERE APPLICANT_SOURCE='Employee Referral Programs'; ALTER TABLE APPLICANT_AUD CHANGE APPLICANT_SOURCE APPLICANT_SOURCE ENUM( 'Internal-Referral', 'Job-Boards','Career-Sites','Recruitment-Agencies','Social-Media','Direct-Applications', 'Campus-Recruitment','Employee-Referral-Programs') DEFAULT NULL; 

ALTER TABLE EMPLOYEE_AUD MODIFY COLUMN FIRST_NAME varchar(50) DEFAULT NULL, MODIFY COLUMN LAST_NAME varchar(50) DEFAULT NULL, MODIFY COLUMN FULL_NAME varchar(70) DEFAULT NULL, MODIFY COLUMN DEPARTMENT_ID int DEFAULT NULL, MODIFY COLUMN LOCATION_ID int DEFAULT NULL, MODIFY COLUMN DESIGNATION_ID int DEFAULT NULL, MODIFY COLUMN EMPLOYMENT_TYPE varchar(100) DEFAULT NULL, MODIFY COLUMN DATE_OF_JOINING datetime DEFAULT NULL, MODIFY COLUMN WORK_PHONE_NUMBER varchar(20) DEFAULT NULL, MODIFY COLUMN WORK_EMAIL_ADDRESS varchar(100) DEFAULT NULL, MODIFY COLUMN CONTRACT_TYPE VARCHAR(100) DEFAULT NULL;  

ALTER TABLE EMPLOYEE_AUD MODIFY COLUMN DELETED tinyint(1) DEFAULT NULL; 

ALTER TABLE EMPLOYEE_GOALS_DETAILS DROP COLUMN TITLE,DROP COLUMN DESCRIPTION,DROP COLUMN SUCCESS_CRITERIA,ADD COLUMN OBJECTIVE TEXT,ADD COLUMN KEY_RESULTS TEXT; 

INSERT INTO HRMS_SYSTEM_CONFIG(KEY_NAME,KEY_VALUE)  VALUES('employmentStatus','In Onboarding'); 

INSERT INTO HRMS_SYSTEM_CONFIG(KEY_NAME,KEY_VALUE)  VALUES('contractType','Indefinite'); 

INSERT INTO HRMS_SYSTEM_CONFIG(KEY_NAME,KEY_VALUE)  VALUES('locationName','Dammam'); 

CREATE TABLE SUCCESSOR (  ID INT AUTO_INCREMENT PRIMARY KEY, DEVELOPMENT_NEED VARCHAR(100) DEFAULT NULL COMMENT 'Description of the development need for the successor', DESIGNATION_ID INT DEFAULT NULL COMMENT 'ID of the designation (role) associated with the successor', RECOMMENDED_CANDIDATE_ID INT DEFAULT NULL COMMENT 'ID of the recommended candidate for the successor role',   PROCESS_INSTANCE_ID VARCHAR(100) DEFAULT NULL,  WORKFLOW_STAGE VARCHAR(100) DEFAULT NULL,  CREATED_TIME DATETIME(6) DEFAULT NULL,  MODIFIED_TIME DATETIME(6) DEFAULT NULL, CREATOR INT DEFAULT NULL, LAST_MODIFIER INT DEFAULT NULL,   CONSTRAINT successordesignation_ibfk_1  FOREIGN KEY (DESIGNATION_ID) REFERENCES DESIGNATION(ID),  CONSTRAINT successor_ibfk_2  FOREIGN KEY (LAST_MODIFIER) REFERENCES User(ID),  CONSTRAINT successor_ibfk_3  FOREIGN KEY (CREATOR) REFERENCES User(ID),    CONSTRAINT employeesuccessoribfk_4  FOREIGN KEY (RECOMMENDED_CANDIDATE_ID) REFERENCES EMPLOYEE(ID),   KEY RECOMMENDED_CANDIDATE_ID (RECOMMENDED_CANDIDATE_ID),KEY DESIGNATION_ID (DESIGNATION_ID), KEY FK4jyd41gcmvmdk740lcwmvooas (CREATOR), KEY FK445sht8j3up6irlr1sdcszyx3 (LAST_MODIFIER) ); 

CREATE TABLE EMPLOYEE_SUCCESSOR (    ID INT AUTO_INCREMENT PRIMARY KEY,  EMPLOYEE_ID INT DEFAULT NULL COMMENT 'ID of the employee associated with this successor record', EMPLOYEE_REVIEW_ID INT DEFAULT NULL COMMENT 'ID of the employee review linked to this successor record', EMPLOYEE_SCORE DOUBLE DEFAULT NULL COMMENT 'Score assigned to the employee during the review or successor process',  FEEDBACK VARCHAR(255) DEFAULT NULL COMMENT 'Feedback provided for the employee during the review process', READINESS_LEVEL VARCHAR(100) DEFAULT NULL COMMENT 'Indicates the readiness level of the employee for succession', 
SUCCESSOR_ID INT NOT NULL COMMENT 'ID of the successor record associated with this employee successor entry',  CONSTRAINT fk_employee  FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(ID),  CONSTRAINT fk_employee_review  FOREIGN KEY (EMPLOYEE_REVIEW_ID) REFERENCES EMPLOYEE_REVIEW(ID), CONSTRAINT fk_successor  FOREIGN KEY (SUCCESSOR_ID) REFERENCES SUCCESSOR(ID),   KEY FK_EMPLOYEE_ID (EMPLOYEE_ID),   KEY FK_EMPLOYEE_REVIEW_ID (EMPLOYEE_REVIEW_ID),   KEY FK_SUCCESSOR_ID (SUCCESSOR_ID) 
); 
