ALTER TABLE `EMPLOYEE_CHILDREN` DROP FOREIGN KEY `employeechildren_ibwuwfk_1`; 

ALTER TABLE `EMPLOYEE_CHILDREN` DROP COLUMN `CHILD_EDUCATION_BENEFIT_ID`; 

ALTER TABLE `EMPLOYEE_CHILDREN` ADD COLUMN `HR_BENEFITS_ID` INT; 

 ALTER TABLE `EMPLOYEE_CHILDREN` ADD CONSTRAINT `fk_employeechildren_hrbenefits` FOREIGN KEY (`HR_BENEFITS_ID`) REFERENCES `HR_BENEFITS` (`ID`); 

ALTER TABLE `JOB_APPLICATION_CONFIGURATION_SCORE` ADD COLUMN `REASON` varchar(1000) DEFAULT NULL; 

 

ALTER TABLE OFFERS 
 ADD COLUMN BASIC_SALARY DOUBLE DEFAULT NULL, 
 ADD COLUMN CRITICAL_SKILLS DOUBLE DEFAULT NULL, 
 ADD COLUMN DELETED tinyint(1) NOT NULL DEFAULT '0', 
 ADD COLUMN END_DATE DATE DEFAULT NULL, 
 ADD COLUMN HRA DOUBLE DEFAULT NULL, 
 ADD COLUMN LOCAL_CURRENCY VARCHAR(10) DEFAULT NULL, 
 ADD COLUMN MOBILE_ALLOWANCE DOUBLE DEFAULT NULL, 
 ADD COLUMN OVERBASE DOUBLE DEFAULT NULL, 
 ADD COLUMN OVERTIME DOUBLE DEFAULT NULL, 
 ADD COLUMN GROSS_SALARY DOUBLE DEFAULT NULL, 
 ADD COLUMN PAY_FREQUENCY VARCHAR(255) DEFAULT NULL, 
 ADD COLUMN EMPLOYEE_MOBILE_FLAG VARCHAR(255) DEFAULT NULL, 
 ADD COLUMN PAY_RATE DOUBLE DEFAULT NULL, 
 ADD COLUMN RELOCATION_ALLOWANCE DOUBLE DEFAULT NULL, 
 ADD COLUMN RELOCATION_ALLOWANCE_DATE DATE DEFAULT NULL, 
 ADD COLUMN SIGN_UP_BONUS DOUBLE DEFAULT NULL, 
 ADD COLUMN NEGO_PCT_OVERBASE DOUBLE DEFAULT NULL, 
 ADD COLUMN NEGO_PCT_CRITICAL DOUBLE DEFAULT NULL, 
 ADD COLUMN SIGN_UP_BONUS_DATE DATE DEFAULT NULL, 
 ADD COLUMN START_DATE DATE DEFAULT NULL, 
 ADD COLUMN STI DOUBLE DEFAULT NULL, 
 ADD COLUMN STI_DATE DATE DEFAULT NULL, 
 ADD COLUMN TA DOUBLE DEFAULT NULL, 
 ADD COLUMN YEARLY_BASIC_SALARY DOUBLE DEFAULT NULL, 
 ADD COLUMN YEARLY_OVERBASE DOUBLE DEFAULT NULL, 
 ADD COLUMN YEARLY_CRITICAL_SKILLS DOUBLE DEFAULT NULL, 
 ADD COLUMN YEARLY_HRA DOUBLE DEFAULT NULL, 
 ADD COLUMN YEARLY_TA DOUBLE DEFAULT NULL, 
 ADD COLUMN YEARLY_MOBILE_ALLOWANCE DOUBLE DEFAULT NULL, 
 ADD COLUMN YEARLY_GROSS_SALARY DOUBLE DEFAULT NULL; 

ALTER TABLE OFFERS CHANGE CANDIDATE_ID APPLICANT_ID int DEFAULT NULL; 

CREATE TABLE `CONFIGURATION_SCORE` (   `ID` int NOT NULL AUTO_INCREMENT,   `ANSWER` text DEFAULT NULL,    `QUESTION` varchar(1000) DEFAULT NULL,    `SUB_SCORE` double DEFAULT NULL,   `CONFIGRUATION_FK` int NOT NULL,   `JOB_APPLICATION_FK` int NOT NULL,   `PROCESS_INSTANCE_ID` varchar(100) DEFAULT NULL,   `WORKFLOW_STAGE` varchar(100) DEFAULT NULL,   `CREATED_TIME` datetime(6) DEFAULT NULL,   `MODIFIED_TIME` datetime(6) DEFAULT NULL,   `CREATOR` int DEFAULT NULL,   `LAST_MODIFIER` int DEFAULT NULL,   PRIMARY KEY (`ID`),   KEY `JOB_APPLICATION_FK` (`JOB_APPLICATION_FK`),   KEY `CONFIGRUATION_FK` (`CONFIGRUATION_FK`),   KEY `FKryunt4ywp525bi3f53jifd5qjamwqqq` (`CREATOR`),   KEY `FKhfqj4fkf32oyx6srfdihcvdfdfqwww` (`LAST_MODIFIER`),   CONSTRAINT `FKhfqj4fkf32oyx6srfdihcvdfdfqwww` FOREIGN KEY (`LAST_MODIFIER`) REFERENCES `User` (`ID`),   CONSTRAINT `FKryunt4ywp525bi3f53jifd5qjamwqqq` FOREIGN KEY (`CREATOR`) REFERENCES `User` (`ID`),   CONSTRAINT `ConfigurationScore_ibfk_1` FOREIGN KEY (`JOB_APPLICATION_FK`) REFERENCES `JOB_APPLICATION` (`ID`),   CONSTRAINT `ConfigurationScore_ibfk_2` FOREIGN KEY (`CONFIGRUATION_FK`) REFERENCES `WEIGHTAGE_CONFIGURATION` (`ID`) ); 

 

alter table WEIGHTAGE_CONFIGURATION add column CONFIGURATION_QUESTIONS text DEFAULT NULL; 

 

CREATE TABLE `OTHER_EXPENSE_BANK_REQUEST` (   `ID` int NOT NULL AUTO_INCREMENT,   `DELETED` tinyint(1) NOT NULL DEFAULT '0',   WPS_FILE_PATH varchar(100) DEFAULT NULL,   `TYPE` enum('Hr Benefit','Business Expense','Business Trip') ,   WORKFLOW_STAGE varchar(100) DEFAULT NULL,  `PROCESS_INSTANCE_ID` varchar(100) DEFAULT NULL,   `START_DATE` datetime DEFAULT NULL,   `END_DATE` datetime DEFAULT NULL,   REQUEST_ID varchar(100) DEFAULT NULL,   CREATED_TIME datetime(6) DEFAULT NULL, MODIFIED_TIME datetime(6) DEFAULT NULL, CREATOR int DEFAULT NULL, LAST_MODIFIER int DEFAULT NULL, PRIMARY KEY (`ID`), KEY `FKryunt4ywp5265bi3f53jifd5qjamwq` (`CREATOR`), KEY `FKhfqj4fkf326oyx6srfdihcvdfdfqw` (`LAST_MODIFIER`), CONSTRAINT `FKOhfqj4fkf326oyx6srfdihcvdfdfqw` FOREIGN KEY (`LAST_MODIFIER`) REFERENCES `User` (`ID`),  CONSTRAINT `FK0ryunt4ywp5265bi3f53jifd5qjamwq` FOREIGN KEY (`CREATOR`) REFERENCES `User` (`ID`)   ); 

ALTER TABLE OTHER_EXPENSE_BANK_REQUEST ADD WEEK_NUM INT DEFAULT NULL,ADD YEAR INT DEFAULT NULL,DROP COLUMN END_DATE,CHANGE START_DATE DATE DATETIME DEFAULT NULL; 

ALTER TABLE FILE_DATA CHANGE WEEK_NUM MONTH int; 

ALTER TABLE RUN_DETAILS  
 ADD COLUMN BASIC_SALARY_AFTER_DEDUCTION DOUBLE DEFAULT NULL COMMENT 'Basic salary after deductions', 
 ADD COLUMN HRA_AFTER_DEDUCTION DOUBLE DEFAULT NULL COMMENT 'Stores HRA after deduction';

ALTER TABLE INTEGRATION_LOG ADD COLUMN PAYROLL_ID INT DEFAULT NULL; 
