ALTER TABLE `EMPLOYEE_GOALS_DETAILS` MODIFY COLUMN `EMPLOYEE_STATUS` ENUM('Not Started', 'On Track', 'At Risk', 'Deferred', 'Completed', 'Off Track') DEFAULT 'Not Started', MODIFY COLUMN `MANAGER_STATUS` ENUM('Not Started', 'On Track', 'At Risk', 'Deferred', 'Completed', 'Off Track') DEFAULT 'Not Started'; 

ALTER TABLE BUSINESS_EXPENSE ADD COLUMN OTHER_EXPENSE_BANK_REQUEST_ID INT DEFAULT NULL COMMENT 'Stores Id of Other Expense Bank Request'; 

ALTER TABLE BUSINESS_TRIP ADD COLUMN OTHER_EXPENSE_BANK_REQUEST_ID INT DEFAULT NULL COMMENT 'Stores Id of Other Expense Bank Request'; 

ALTER TABLE `HR_BENEFITS` ADD COLUMN `OTHER_EXPENSE_BANK_REQUEST_ID` INT DEFAULT NULL COMMENT 'Stores Id of Other Expense Bank Request’; 

ALTER TABLE BUSINESS_TRIP ADD COLUMN TRAVEL_SCOPE ENUM('INTERNAL', 'EXTERNAL') DEFAULT NULL; 

ALTER TABLE PAYROLL_RUN ADD COLUMN `TOTAL_BASIC_SALARY` double DEFAULT NULL COMMENT 'Total basic salary for the payroll', ADD COLUMN `TOTAL_ALLOWANCES` double DEFAULT NULL COMMENT 'Total allowances amount for the payroll'; 

CREATE TABLE `JOB_APPLICATION_BATCH` (   `ID` int NOT NULL AUTO_INCREMENT,   `PROCESS_INSTANCE_ID` varchar(100) DEFAULT NULL,   `WORKFLOW_STAGE` varchar(100) DEFAULT NULL,   `CREATED_TIME` datetime(6) DEFAULT NULL,   `MODIFIED_TIME` datetime(6) DEFAULT NULL,   `CREATOR` int DEFAULT NULL,   `LAST_MODIFIER` int DEFAULT NULL,   PRIMARY KEY (`ID`),   KEY `FKryunt4ywp525bi3f53jifd5qj5amwq` (`CREATOR`),   KEY `FKhfqj4fkf32oyx6srfdihcvdfdfq2w` (`LAST_MODIFIER`),   CONSTRAINT `FKhfqj4fkf32oyx6srfdihcvdfdfq2w` FOREIGN KEY (`LAST_MODIFIER`) REFERENCES `User` (`ID`),   CONSTRAINT `FKryunt4ywp525bi3f53jifd5qj5amwq` FOREIGN KEY (`CREATOR`) REFERENCES `User` (`ID`) ); 

ALTER TABLE JOB_APPLICATION ADD COLUMN JOB_APPLICATION_BATCH_ID INT DEFAULT NULL; 

  

ALTER TABLE JOB_APPLICATION 
 ADD CONSTRAINT FK_JOB_APPLICATION_JOB_APPLICATION_BATCH FOREIGN KEY (JOB_APPLICATION_BATCH_ID) REFERENCES JOB_APPLICATION_BATCH(ID); 

 

ALTER TABLE `EMPLOYEE_GOALS_DETAILS` MODIFY `TEXT1` TEXT COMMENT 'Stores the Prompt given',MODIFY `DESCRIPTION` VARCHAR(500) DEFAULT NULL COMMENT 'Stores Description given by prompt',MODIFY `SUCCESS_CRITERIA` VARCHAR(500) DEFAULT NULL COMMENT 'Stores Success Criteria given by prompt', MODIFY `TITLE` VARCHAR(200) DEFAULT NULL COMMENT 'Title of the employee goal'; 

 

ALTER TABLE BUSINESS_EXPENSE ADD COLUMN REMARK LONGTEXT COMMENT'It stores the remark'; 

ALTER TABLE HR_BENEFITS ADD COLUMN REMARK LONGTEXT COMMENT'It stores the remark'; 
