ALTER TABLE EMPLOYEE_DEPENDENT_DETAILS ADD COLUMN ACCOMMODATION_REQUIREMENT TINYINT(1) DEFAULT 0, ADD COLUMN ATTACHMENT VARCHAR(200) DEFAULT NULL, ADD COLUMN SAUDI_ID VARCHAR(255) DEFAULT NULL, ADD COLUMN FAMILY_CARD VARCHAR(200) DEFAULT NULL, ADD COLUMN NATIONALITY VARCHAR(255) DEFAULT NULL; 

ALTER TABLE EMPLOYEE_NATIONAL_IDENTIFICATION ADD COLUMN IQAMA_NUMBER VARCHAR(255) DEFAULT NULL; 

ALTER TABLE EMPLOYEE_EMERGENCY_CONTACT ADD COLUMN ADDRESS VARCHAR(255) DEFAULT NULL, ADD COLUMN CITY VARCHAR(255) DEFAULT NULL, ADD COLUMN COUNTRY VARCHAR(255) DEFAULT NULL,ADD COLUMN POSTAL_CODE VARCHAR(255) DEFAULT NULL; 

ALTER TABLE EMPLOYEE ADD COLUMN VISA_CONTRACT VARCHAR(200) DEFAULT NULL, ADD COLUMN EDUCATION_LETTER VARCHAR(200) DEFAULT NULL, ADD COLUMN VISA_LETTER VARCHAR(200) DEFAULT NULL, ADD COLUMN CV VARCHAR(200) DEFAULT NULL, ADD COLUMN PRESENT_SHORT_ADDRESS VARCHAR(255) DEFAULT NULL, ADD COLUMN PRESENT_BUILDING_ADDRESS VARCHAR(255) DEFAULT NULL, ADD COLUMN PRESENT_CITY VARCHAR(100) DEFAULT NULL,ADD COLUMN PRESENT_COUNTRY VARCHAR(100) DEFAULT NULL, ADD COLUMN PRESENT_POSTAL_ADDRESS VARCHAR(100) DEFAULT NULL, ADD COLUMN NATIONAL_ADDRESS VARCHAR(255) DEFAULT NULL, ADD COLUMN PROBATION_PERIOD_END_DATE DATETIME DEFAULT NULL, ADD COLUMN INDUCTION_SESSION_DATE DATETIME DEFAULT NULL, ADD COLUMN FAMILY_CARD VARCHAR(200) DEFAULT NULL, ADD COLUMN SAUDI_ARAMCO_BADGE VARCHAR(200) DEFAULT NULL, ADD COLUMN BADGE_NO VARCHAR(50) DEFAULT NULL, ADD COLUMN BADGE_EXPIRY_DATE DATETIME DEFAULT NULL, ADD COLUMN ARAMCO_DIGITAL_EMAIL_ID VARCHAR(255) DEFAULT NULL,ADD COLUMN MEDICAL_REPORT VARCHAR(200) DEFAULT NULL, ADD COLUMN ONBOARDING_SPECIALIST_NAME VARCHAR(255) DEFAULT NULL, ADD COLUMN ONBOARDING_SPECIALIST_EMAIL VARCHAR(255) DEFAULT NULL , ADD COLUMN WORK_PERMIT_NUMBER VARCHAR(50) DEFAULT NULL, ADD COLUMN WORK_PERMIT_EXPIRY_DATE DATETIME DEFAULT NULL,ADD COLUMN RELOCATION_DATE DATETIME DEFAULT NULL; 

ALTER TABLE EMPLOYEEEDUCATIONDETAILS ADD COLUMN ADDITIONAL_NOTES longtext, ADD COLUMN COUNTRY_OF_STUDY VARCHAR(100) DEFAULT NULL, ADD COLUMN DEGREE_START_DATE DATETIME DEFAULT NULL, ADD COLUMN DEGREE_END_DATE DATETIME DEFAULT NULL, ADD COLUMN GRADE VARCHAR(50) DEFAULT NULL, ADD COLUMN STUDENT_ID VARCHAR(50) DEFAULT NULL, ADD COLUMN CITY VARCHAR(100) DEFAULT NULL, ADD COLUMN EDUCATION_LEVEL enum('High School', 'Bachelors', 'Masters', 'Doctorate', 'Other') DEFAULT NULL; 

ALTER TABLE ASSET ADD COLUMN MANUFACTURER VARCHAR(100) DEFAULT NULL, ADD COLUMN PURCHASE_DATE DATETIME DEFAULT NULL, ADD COLUMN WARRANTY_EXPIRY_DATE DATETIME DEFAULT NULL, ADD COLUMN DEPARTMENT VARCHAR(100) DEFAULT NULL, ADD COLUMN LOCATION VARCHAR(100) DEFAULT NULL, ADD COLUMN STATUS enum('Active','Inactive', 'Repair', 'Retired') DEFAULT NULL, ADD COLUMN ASSET_TAG VARCHAR(100) DEFAULT NULL, ADD COLUMN IP_ADDRESS VARCHAR(50) DEFAULT NULL, ADD COLUMN MAC_ADDRESS VARCHAR(50) DEFAULT NULL, ADD COLUMN OPERATING_SYSTEM VARCHAR(100) DEFAULT NULL, ADD COLUMN SOFTWARE_INSTALLED longtext,ADD COLUMN CONFIGURATION_DETAILS longtext,ADD COLUMN VENDOR_DETAILS VARCHAR(255) DEFAULT NULL,ADD COLUMN LAST_MAINTENANCE_DATE DATETIME DEFAULT NULL; 

ALTER TABLE ASSET ADD COLUMN PURCHASE_PRICE double DEFAULT NULL; 

ALTER TABLE EMPLOYEE_WORK_EXPERIENCE ADD COLUMN PREVIOUS_EMPLOYER_CONTACT VARCHAR(255), ADD COLUMN PREVIOUS_EMPLOYER_EMAIL VARCHAR(255), ADD COLUMN INDUSTRY VARCHAR(255), ADD COLUMN SKILLS VARCHAR(255); 

ALTER TABLE ACCOUNT_DETAILS ADD COLUMN BANK_DOCUMENT VARCHAR(200), ADD COLUMN IBAN_CERTIFICATE VARCHAR(200); 

ALTER TABLE EMPLOYEE_DEPENDENT_DETAILS_AUD ADD COLUMN ACCOMMODATION_REQUIREMENT TINYINT(1) DEFAULT 0, ADD COLUMN ATTACHMENT VARCHAR(200) DEFAULT NULL, ADD COLUMN SAUDI_ID VARCHAR(255) DEFAULT NULL, ADD COLUMN FAMILY_CARD VARCHAR(200) DEFAULT NULL, ADD COLUMN NATIONALITY VARCHAR(255) DEFAULT NULL; 

ALTER TABLE EMPLOYEE_NATIONAL_IDENTIFICATION_AUD ADD COLUMN IQAMA_NUMBER VARCHAR(255) DEFAULT NULL; 

ALTER TABLE EMPLOYEE_EMERGENCY_CONTACT_AUD ADD COLUMN ADDRESS VARCHAR(255) DEFAULT NULL, ADD COLUMN CITY VARCHAR(255) DEFAULT NULL, ADD COLUMN COUNTRY VARCHAR(255) DEFAULT NULL,ADD COLUMN POSTAL_CODE VARCHAR(255) DEFAULT NULL; 


Alter table APPLICANT modify column `SKILL_SET` varchar(1000) DEFAULT NULL;

ALTER TABLE EMPLOYEE_AUD ADD COLUMN VISA_CONTRACT VARCHAR(200) DEFAULT NULL, ADD COLUMN EDUCATION_LETTER VARCHAR(200) DEFAULT NULL, ADD COLUMN VISA_LETTER VARCHAR(200) DEFAULT NULL, ADD COLUMN CV VARCHAR(200) DEFAULT NULL, ADD COLUMN PRESENT_SHORT_ADDRESS VARCHAR(255) DEFAULT NULL, ADD COLUMN PRESENT_BUILDING_ADDRESS VARCHAR(255) DEFAULT NULL, ADD COLUMN PRESENT_CITY VARCHAR(100) DEFAULT NULL,ADD COLUMN PRESENT_COUNTRY VARCHAR(100) DEFAULT NULL, ADD COLUMN PRESENT_POSTAL_ADDRESS VARCHAR(100) DEFAULT NULL, ADD COLUMN NATIONAL_ADDRESS VARCHAR(255) DEFAULT NULL, ADD COLUMN PROBATION_PERIOD_END_DATE DATETIME DEFAULT NULL, ADD COLUMN INDUCTION_SESSION_DATE DATETIME DEFAULT NULL, ADD COLUMN FAMILY_CARD VARCHAR(200) DEFAULT NULL, ADD COLUMN SAUDI_ARAMCO_BADGE VARCHAR(200) DEFAULT NULL, ADD COLUMN BADGE_NO VARCHAR(50) DEFAULT NULL, ADD COLUMN BADGE_EXPIRY_DATE DATETIME DEFAULT NULL, ADD COLUMN ARAMCO_DIGITAL_EMAIL_ID VARCHAR(255) DEFAULT NULL,ADD COLUMN MEDICAL_REPORT VARCHAR(200) DEFAULT NULL, ADD COLUMN ONBOARDING_SPECIALIST_NAME VARCHAR(255) DEFAULT NULL, ADD COLUMN ONBOARDING_SPECIALIST_EMAIL VARCHAR(255) DEFAULT NULL , ADD COLUMN WORK_PERMIT_NUMBER VARCHAR(50) DEFAULT NULL, ADD COLUMN WORK_PERMIT_EXPIRY_DATE DATETIME DEFAULT NULL,ADD COLUMN RELOCATION_DATE DATETIME DEFAULT NULL; 
